const COMMENT_LABEL = {
    VALID: 'VALID',
    SCAM: 'SCAM',
    SELF_PROMO: 'SELF_PROMO',
    OTHER_PROMO: 'OTHER_PROMO',
    SPONSOR: 'SPONSOR',
    EXPLICIT: 'EXPLICIT',
    LINK_ONLY: 'LINK_ONLY',
    LINK_SPAM: 'LINK_SPAM',
    MALICIOUS_LINKS: 'MALICIOUS_LINKS',
    OTHER_SPAM: 'OTHER_SPAM',
    REPLY_TO_SCAM: 'REPLY_TO_SCAM',
};
